<form method="post" class="form-horizontal" id="form-bind">
<?php 
	print View::formValidate();
	print View::input('page', 'hidden', $this->pageName);
	print View::input('gid', 'hidden', get('gid'));
	print View::input('ids', 'hidden');
	
	print '<div class="form-group">';
	print '<div class="col-sm-6"><ul class="list-group" id="list-all"></ul></div>';
	print '<div class="col-sm-6"><ul class="list-group" id="list-current"></ul></div>';
	print '</div>';
	
	print View::input('save', 'submit');
?>
</form>