<div class="panel panel-default">
	<div class="panel-heading">
		<?php print $this->page->linkText(); ?>
		<div class="pull-right">
			<?php print View::link(Route::FIELD_ADD, '', 'page=' . $this->page->name, null, 'btn btn-xs btn-primary glyphicon glyphicon-plus', null, 'left'); ?>
			<?php print View::link(Route::FIELD_BIND, '', 'page=' . $this->page->name, null, 'btn btn-xs btn-primary glyphicon glyphicon-user', null, 'top'); ?>
		</div>
	</div>
	<table class="table table-middle">
		<thead><tr>
			<th><?php print View::str('name'); ?></th>
			<th><?php print View::str('type'); ?></th>
			<th><?php print View::str('mandatory'); ?></th>
			<th><?php print View::str('weight'); ?></th>
			<th></th>
		</tr></thead>
		<tbody>
			<?php
			$html = '';
			foreach ($this->fields as $field) {
				$class = '';
				if ($field->isSystem()) $class = ' class="success"';
				
				$html .= '<tr' . $class . '>';
				
				$html .= '<form method="get">';
				$html .= View::input('page', 'hidden', $this->page->name);
				$html .= View::input('id', 'hidden', $field->id);
				
				$html .= '<td>' . $field->name . '</td>';
				$html .= '<td>' . $field->type . '</td>';
				$html .= '<td>' . View::bool2icon($field->mandatory) . '</td>';
				$html .= '<td>' . View::input('weight', 'numeric', $field->weight) . '</td>';
				
				$html .= '<td>';
				//$html .= View::input('', 'submit', 'btn btn-xs btn-success glyphicon glyphicon-ok');
				if ($field->canDelete()) $html .= '&nbsp;' . View::link(Route::FIELD_DELETE, '', 'id=' . $field->id, 'edit', 'btn btn-xs btn-danger glyphicon glyphicon-remove', null, 'top');
				$html .= '</td>';
				
				$html .= '</form>';
				
				$html .= '</tr>';
				
			}
			print $html;
			?>
		</tbody>
	</table>
</div>