<form method="post" class="form-horizontal">
	<?php 
		print View::input('send', 'hidden', '1');
		print View::formNormal('email', 'email');
		print View::formNormal('password', 'password');
		print View::formNormal('username');
		print View::formNormal('group', 'select', $this->groups);
		print View::formNormal('gid');
	?>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?php print View::input('add', 'submit'); ?>
		</div>
	</div>
</form>