<form method="post" class="form-horizontal">
	<input type="hidden" name="send" value="1">
	<div class="form-group">
		<label for="inputEmail" class="col-sm-2 control-label"><?php echo $this->str('EMAIL'); ?></label>
		<div class="col-sm-10">
			<input type="email" class="form-control" name="email" id="inputEmail" placeholder="<?php echo $this->str('EMAIL'); ?>">
		</div>
	</div>
	<div class="form-group">
		<label for="inputPassword" class="col-sm-2 control-label"><?php echo $this->str('PASSWORD'); ?></label>
		<div class="col-sm-10">
			<input type="password" class="form-control" name="password" id="inputPassword" placeholder="<?php echo $this->str('PASSWORD'); ?>">
		</div>
	</div>
	<div class="form-group">
		<label for="inputFirstname" class="col-sm-2 control-label"><?php echo $this->str('FIRSTNAME'); ?></label>
		<div class="col-sm-10">
			<input type="text" class="form-control" name="firstname" id="inputFirstname" placeholder="<?php echo $this->str('FIRSTNAME'); ?>">
		</div>
	</div>
	<div class="form-group">
		<label for="inputLastname" class="col-sm-2 control-label"><?php echo $this->str('LASTNAME'); ?></label>
		<div class="col-sm-10">
			<input type="text" class="form-control" name="lastname" id="inputLastname" placeholder="<?php echo $this->str('LASTNAME'); ?>">
		</div>
	</div>
	<div class="form-group">
		<label for="inputGroup" class="col-sm-2 control-label"><?php echo $this->str('GROUP'); ?></label>
		<div class="col-sm-10">
			<select class="form-control" id ="inputGroup" name="group">
				<?php foreach ($this->groups as $group)  echo '<option value="' . $group . '">' . $this->str($group). '</option>'; ?>
			</select>
		</div>
	</div>
	<div class="form-group">
		<label for="inputUID" class="col-sm-2 control-label"><?php echo $this->str('UID'); ?></label>
		<div class="col-sm-10">
			<input type="text" class="form-control" name="uid" id="inputUID" placeholder="<?php echo $this->str('UID'); ?>">
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<button type="submit" class="btn btn-primary"><?php echo $this->str('SIGNUP'); ?></button>
		</div>
	</div>
</form>