<form method="post" class="form-horizontal">
	<?php 
		print View::input('send', 'hidden', '1');
		print View::group('email', 'email');
		print View::group('password', 'password');
		print View::group('firstname');
		print View::group('lastname');
		print View::group('group', 'select', $this->groups);
		print View::group('uid');
	?>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<?php print View::input('add', 'submit'); ?>
		</div>
	</div>
</form>