<div class="panel panel-default">
	<div class="panel-heading"><?php print sprintf($this->str('all_users_result'), count($this->users)); ?></div>
	
	<div class="panel-body">
		<ul class="nav nav-pills">
			<?php
				foreach ($this->groups as $group) {
					$disabled = $this->currentGroup==$group;
					print	'<li role="presentation"' . ($disabled ? ' class="disabled"' : '') . '>'.
							'<a href="' . ($disabled ? '#' : '?group=' . $group) . '">' . $this->str($group) . '</a>'.
							'</li>';
				}
			?>
		</ul>
	</div>

	<table class="table">
		<thead>
			<tr>
				<?php
				foreach ($this->fields as $th) {
					print '<th>' . $this->str($th) . '</th>';
				}
				?>
			</tr>
		</thead>
		<tbody>
			<?php
			$users = '';
			foreach ($this->users as $n => $user) {
				$users .= '<tr>';
				foreach ($this->fields as $td) {
					$users .= '<td>' . $user->$td . '</td>';
				}
				$users .= '</tr>';
			}
			print $users;
			?>
		</tbody>
	</table>
</div>
