

<table class="table">
	<thead>
		<tr>
			<th>#</th>
			<?php
			foreach (array('username', 'email', 'group', 'uid') as $th) {
				print '<th>' . $this->str($th) . '</th>';
			}
			?>
		</tr>
	</thead>
	<tbody>
		<?php
		foreach ($this->users as $n => $user) {
			print 	'<tr>
					<th scope="row">' . ($n+1) . '</th>
					<td>' . $user->firstname . ' ' . $user->lastname . '</td>
					<td>' . $user->email . '</td>
					<td>' . $user->group . '</td>
					<td>' . $user->uid . '</td>
					</tr>';
		}
		?>
	</tbody>
</table>
