<dl class="dl-horizontal">
	<dt><?php echo $this->str('firstname'); ?>:</dt>
	<dd><?php echo Application::$user->firstname; ?></dd>
	<dt><?php echo $this->str('lastname'); ?>:</dt>
	<dd><?php echo Application::$user->lastname; ?></dd>
	<dt><?php echo $this->str('email'); ?>:</dt>
	<dd><?php echo Application::$user->email; ?></dd>
	<dt><?php echo $this->str('group'); ?>:</dt>
	<dd><?php echo Application::$user->group; ?></dd>
</dl>