<?php

return array(
	'EMAIL' => 'Email',
	'PASSWORD' => 'Password',
	'SIGNIN' => 'Sign in',
	'SIGN_SUCCESSFULY' => 'You successfully sign in...',
	'LOGOUT_SUCCESSFULY' => 'You successfully log out...',
	'REDIRECT' => '<b>%d</b> seconds later you will be redirected. If it does not, click %s',
	'HERE' => 'here',
	'GROUP' => 'Group',
	'ACCESS_DENIED' => 'Access is denied',
	'NOT_FOUND' => '%s not found',
	'SIGNUP' => 'Sign Up',
	'ANONYMOUS' => 'Anonymous',
	'VIEWER' => 'Viewer',
	'CLIENT' => 'Client',
	'MANAGER' => 'Manager',
	'ADMIN' => 'Admin',
	'IN_PROGRESS' => 'In Progress...',
	'SUCCESS_SAVE' => 'Success Saved!',
	'MUST_ENTER' => 'You must fill in the <b>%s</b>',
	'ADD' => 'Add',
	'USERNAME' => 'Username',
	'ALL_USERS_RESULT' => 'Results <b>%d</b> users',
	'ALL_ORDERS_RESULT' => 'Results <b>%d</b> orders',
	'TITLE' => 'Title',
	'STATUS' => 'Status',
	'DATE_DUE' => 'Due date',
	'GID' => 'Group ID',
	'VIEW' => 'View',
	'CANCEL' => 'Cancel',
	'PHOTOPOLYMER' => 'Photopolymer',
	'URGENT' => 'Urgent',
	'PHOTOPOLYMERS' => 'Photopolymers',
	'SET' => 'Set',
	
	'MENU_INDEX' => 'Index',
	'MENU_LOGIN' => 'Login',
	'MENU_ORDERADD' => 'Add Order',
	'MENU_USERADD' => 'Add User',
	'MENU_USERALL' => 'All users',
	'MENU_USER' => 'User',
	'MENU_ORDERALL' => 'Orders',
	'MENU_ADMIN' => 'Administration',
	'MENU_VIEWAS' => 'View as',
	'MENU_LOGOUT' => 'Logout',
	'MENU_ORDERVIEW' => 'Order View',
	'MENU_ORDEREDIT' => 'Order Edit',
	'MENU_ORDERDUPLICATE' => 'Order Duplicate',
	'MENU_VIEWASCANCEL' => 'Cancel',
	'MENU_PHOTOPOLYMERS' => 'Photopolymers',
	'MENU_GROUPPHOTOPOLYMERS' => 'By group',
	
	'MENU_TITLE_USER' => 'This section is intended to work with users, such as viewing, editing and adding new members', 
	'MENU_TITLE_ORDERALL' => 'The main section, order management and tracking',
	'MENU_TITLE_ADMIN' => 'Section for site administrators', 
	'MENU_TITLE_VIEWAS' => 'To view the site for any group', 
	'MENU_TITLE_ORDERADD' => 'Add new order',
	'MENU_TITLE_ORDERVIEW' => 'View this order',
	'MENU_TITLE_ORDEREDIT' => 'Edit this order',
	'MENU_TITLE_ORDERDUPLICATE' => 'Duplicate this order',
	'MENU_TITLE_ORDERDELETE' => 'Delete this order',
	'MENU_TITLE_PHOTOPOLYMERS' => 'Photopolymers and setting binding photopolymers groups',
	'MENU_TITLE_LOGOUT' => 'Get out of personal cabinet',
	
	'WARNING_VIEW_AS' => 'You are viewing this page as <b>%s</b> [%s]',
	
	'ERROR_SIGN_IN' => 'incorrect email/password',
	'ERROR_NEED_SIGN' => 'You need sign in',
	'ERROR_IS_NOT_IREDIRECT' => 'Controller <b>%s</b> not implemented IRedirect',
	'ERROR_IS_NOT_ICATALOG' => 'Controller <b>%s</b> not implemented ICatalog',
	'ERROR_ORDER_NOT_FOUND' => 'Order not found',
);

?>