<?php

return array(
	'EMAIL' => 'Email',
	'PASSWORD' => 'Password',
	'SIGNIN' => 'Sign in',
	'SIGN_SUCCESSFULY' => 'You successfully sign in...',
	'LOGOUT_SUCCESSFULY' => 'You successfully log out...',
	'REDIRECT' => '<b>%d</b> seconds later you will be redirected. If it does not, click %s',
	'HERE' => 'here',
	'GROUP' => 'Group',
	'ACCESS_DENIED' => 'Access is denied',
	'NOT_FOUND' => '%s not found',
	'SIGNUP' => 'Sign Up',
	'ANONYMOUS' => 'Anonymous',
	'CLIENT' => 'Client',
	'MANAGER' => 'Manager',
	'ADMIN' => 'Admin',
	'IN_PROGRESS' => 'In Progress...',
	'SUCCESS_SAVE' => 'Success Saved!',
	'MUST_ENTER' => 'You must fill in the <b>%s</b>',
	'ADD' => 'Add',
	'USERNAME' => 'Username',
	'ALL_USERS_RESULT' => 'Results <b>%d</b> users',
	'ALL_ORDERS_RESULT' => 'Results <b>%d</b> orders',
	'ORDER_NAME' => 'Order',
	'ORDER_STATUS' => 'Status',
	'ORDER_DATE_DUE' => 'Due date',
	'ORDER_TABLE_HELP' => 'One click for item - selected item, and double click enter to view order',
	'GID' => 'Group ID',
	
	'TOOLTIP_ORDER_ADD' => 'Add new order',
	'TOOLTIP_ORDER_VIEW' => 'View this order',
	'TOOLTIP_ORDER_EDIT' => 'Edit this order',
	'TOOLTIP_ORDER_DUPLICATE' => 'Duplicate this order',
	'TOOLTIP_ORDER_DELETE' => 'Delete this order',
	
	'MENU_ORDERADD' => 'Add Order',
	'MENU_USERADD' => 'Add User',
	'MENU_USERALL' => 'All users',
	'MENU_PROFILE' => 'Profile',
	'MENU_ORDERALL' => 'Orders',
	'MENU_LOGOUT' => 'Logout',
	
	'ERROR_SIGN_IN' => 'incorrect email/password',
	'ERROR_NEED_SIGN' => 'You need sign in',
	'ERROR_IS_NOT_IREDIRECT' => 'Controller <b>%s</b> not implemented IRedirect',
	'ERROR_ORDER_NOT_FOUND' => 'Order not found',
);

?>