<?php
	if (!$this instanceof ICatalog) {
		print '<div class="alert alert-danger" role="alert">' . sprintf($this->str('error_is_not_icatalog'), Application::$routes->current->name) . '</div>';
		die;
	}
	
	$routes = $this->getRoutes();
	
	$list = '';
	$list .= '<div class="list-group">';
	
	foreach ($routes as $route) {
		if (!$route->isVisible()) continue;
		$list .= '<a href="' . $route->path . '" class="list-group-item">';
		$list .= '<h4 class="list-group-item-heading">' . $route->menuName() . '</h4>';
		$list .= '<p class="list-group-item-text">' . $route->menuTitle() . '</p>';
		$list .= '</a>';
	}
	
	$list .= '</div>';
	
	print $list;
?>