<?php
	if (!$this instanceof ICatalog) {
		print '<div class="alert alert-danger" role="alert">' . sprintf(Application::str('error_is_not_implemented'), Application::$routes->current->name, 'ICatalog') . '</div>';
		die;
	}
	
	$routes = $this->getRoutes();
	
	$list = '';
	$list .= '<div class="list-group">';
	
	foreach ($routes as $route) {
		if ($route->isVisible())
			$list .= View::link($route->name, '<h4 class="list-group-item-heading">' . $route->linkText() . '</h4><p class="list-group-item-text">' . $route->linkTitle() . '</p>', null, null, 'list-group-item');
	}
	
	$list .= '</div>';
	
	print $list;
?>