<?php
	if (!$this instanceof IConfirm) {
		print '<div class="alert alert-danger" role="alert">' . sprintf(View::str('error_is_not_implemented'), Application::$routes->current->name, 'IConfirm') . '</div>';
		die;
	}
	
?>

<div class="alert alert-success" role="alert"><?php echo $this->getConfirm(); ?></div>

<form method="post" class="form-horizontal">
	<?php print View::formValidate(); ?>
	<button type="submit" class="btn btn-primary"><?php print View::str('yes'); ?></button>
	<a class="btn btn-warning" href="javascript:history.back()"><?php print View::str('no'); ?></a>
</form>