<?php

print printRoutes(Application::$routes->all);

function printRoutes($v) {
	$str = '<ul class="menu">';
	
	$n = 0;
	
	foreach ($v as $route) {
		if (!$route->isVisible()) continue;
		
		$active = Application::$routes->equalRoute($route);
		$collapsed = count($route->routes)>0;
		$finded = $active || findInArray($route->routes);
		$expanded = $collapsed && $finded;
		$li = 'leaf';
		if ($expanded) $li = 'expanded';
		else if ($collapsed) $li = 'collapsed'; 
		if ($finded) $li .= ' active-trail';
		if ($n==0) $li .= ' first';
		if ($n==count($v)-1) $li .= ' last';
		
		$str .= '<li class="' . $li . '">';
		$str .= '<a href="' . $route->path . '"' . ($active ? ' class="active"' : '') . '>' . $route->menuName() . '</a>';
		if ($expanded) {
			$str .= printRoutes($route->routes);
		}
		$str .= '</li>';
		
		$n++;
	}
	
	$str .= '</ul>';
	
	return $str;
}

function findInArray($j) {
	foreach ($j as $route) {
		if (Application::$routes->equalRoute($route) || findInArray($route->routes)) return true;
	}
	return false;
}

?>