<?php
	if (!$this instanceof IRedirect) {
		print '<div class="alert alert-danger" role="alert">' . sprintf(View::str('error_is_not_implemented'), Application::$routes->current->name, 'IRedirect') . '</div>';
		die;
	}
	
	$redirect = $this->getRedirect();
	$route = Application::$routes->parseUrl($redirect->url);
	
	if (is_null($route)) die;
	
	$route->path = $redirect->url;
?>

<div class="alert alert-success" role="alert"><?php echo  $redirect->message; ?></div>
<p><?php echo sprintf(View::str('redirect'), $redirect->sTimeout(), View::link($route->name, View::str('here'))); ?></p>
<?php echo '<script type="text/javascript">redirect("' . $route->path . '", ' . $redirect->timeout . ');</script>'; ?>