<form method="get" action="<?php print $this->route->path; ?>" class="form-horizontal">
<?php 
	print View::formNormal('key');
	print View::formOffset('edit', 'submit');
?>
</form>

<?php
foreach ($this->countByLang as $lang => $count) {
	$percent = round($count/$this->total*100);
	$html = '<p><kbd>' . $lang . '</kbd> <b>' . $count . '</b> ' . View::str('locales') . '</p>';
	$html .= '<div class="progress">';
	$html .= '<div class="progress-bar" role="progressbar" aria-valuenow="' . $percent . '" aria-valuemin="0" aria-valuemax="100" style="min-width: 2em; width: ' . $percent . '%">';
	$html .= $percent . '%';
	$html .= '</div></div>';
	print $html;
}
?>