<form method="post" class="form-horizontal" enctype="multipart/form-data">
<?php 
	print $this->form->render();
	
	print View::formOffset('files', 'files');
	if (UserAccess::check(UserAccess::COMMENT_ADD)) {
		print View::formOffset('comment', 'textarea');
	}
	
	print View::formOffset('buttons', 'any', 
		View::input('add', 'submit') . '&nbsp;' .
		View::link('OrderAll', View::str('cancel'), null, null, 'btn btn-warning')
	);
	
?>
</form>
