<?php
if ($this->canComment) {
	print '<form method="post" action="#comments" class="form-horizontal" enctype="multipart/form-data">';
	print View::formValidate();
	print View::input('comment', 'textarea');
	print '<br>';
	print View::input('files', 'files', $this->getFileAvailableExtensions(), $this->getFileMaxSize());
	print '<br>';
	print View::input('submit', 'submit');
	print '</form><hr>';
}
?>

<?php
	$html = '<div id="comments">';
	foreach ($this->comments as $comment) {
		$skin = '';
		switch ($comment->status) {
			case Order::DISAPPROVED:
				$skin = 'danger';
			break;
			default:
				$skin = 'primary';
		}
		
		$html .= '<div class="panel panel-' . $skin . '">';
		$html .= '<div class="panel-heading">' . $comment->username . ' - ' . $comment->date;
		if ($comment->isOwner() && !$comment->isEditExpired()) {
			$html .= '<div class="pull-right">' . View::link(Route::COMMENT_DELETE, '<span class="glyphicon glyphicon-remove" aria-hidden="true"></span>', 'id=' . $comment->id) . '</div>';
		}
		$html .= '</div>';
		$html .= '<div class="panel-body">' . $comment->message . '</div>';
		if (isset($this->comment_attachments[$comment->id])) {
			$html .= '<div class="panel-footer">' . View::attachments($this->comment_attachments[$comment->id]) . '</div>';
		}
		$html .= '</div>';
	}
	$html .= '</div>';
	print $html;
?>