<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="<?php print View::str('close'); ?>"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalLabel"><?php print View::str('filter'); ?></h4>
			</div>
			<form method="get" class="form-horizontal">
				<div class="modal-body">
					<?php
						print View::formNormal('status', 'multiple', Order::statuses());
					?>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php print View::str('close'); ?></button>
					<?php print View::input('apply', 'submit'); ?>
				</div>
			</form>
		</div>
	</div>
</div>