<div class="modal fade" id="filterModal" tabindex="-1" role="dialog" aria-labelledby="modalLabel">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="<?php print View::str('close'); ?>"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="modalLabel"><?php print View::str('filter'); ?></h4>
			</div>
			<form method="get" class="form-horizontal">
				<div class="modal-body">
					<?php
						print View::input('sort', 'hidden', $this->order_by->field);
						print View::input('by', 'hidden', $this->order_by->by);
						print View::formSmall('status', 'multiple', $this->order_filter->getStatuses(), false, false, $this->order_filter->status);
						
						$date_due = '<div class="col-sm-5">' . View::input('date_due_start', 'date', $this->order_filter->date_due_start, false) . '</div>' .
									'<div class="col-sm-5">' . View::input('date_due_end', 'date', $this->order_filter->date_due_end, false) . '</div>';
						print View::formAny('date_due', $date_due, 2);
						
						$date_created =	'<div class="col-sm-5">' . View::input('date_created_start', 'date', $this->order_filter->date_created_start, false) . '</div>' .
										'<div class="col-sm-5">' . View::input('date_created_end', 'date', $this->order_filter->date_created_end, false) . '</div>';
						print View::formAny('date_created', $date_created, 2);
					?>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-default" data-dismiss="modal"><?php print View::str('close'); ?></button>
					<?php print View::input('apply', 'submit'); ?>
				</div>
			</form>
		</div>
	</div>
</div>