<div class="panel panel-default">
	<div class="panel-heading"><?php print sprintf(View::str('all_orders_result'), count($this->orders)); ?>
		<div class="pull-right">
			<?php print View::link('OrderAdd', '', null, 'add', 'btn btn-xs btn-primary glyphicon glyphicon-plus', null, null, 'left'); ?>
			<?php print View::link('OrderView', '', null, 'view', 'btn-action btn btn-xs btn-primary glyphicon glyphicon-eye-open disabled', null, 'top'); ?>
			<?php print View::link('OrderEdit', '', null, 'edit', 'btn-action btn btn-xs btn-primary glyphicon glyphicon-pencil disabled', null, 'top'); ?>
			<?php print View::link('OrderDuplicate', '', null, 'duplicate', 'btn-action btn btn-xs btn-primary glyphicon glyphicon-duplicate disabled', null, 'right'); ?>
		</div>
	</div>
	
	<table class="table table-hover">
		<thead>
			<tr>
				<?php
				foreach ($this->fields as $th) {
					print '<th>' . View::str( $th ) . '</th>';
				}
				print '<th>' . View::str('username') . '</th>';
				?>
			</tr>
		</thead>
		<tbody>
			<?php
			$orders = '';
			foreach ($this->orders as $n => $order) {
				$classes = array();
				
				$classes[] = 'order_row';
				$classes[] = 'noselect';
				$classes[] = 'cursor_pointer';
				
				if ($order->isCanceled()) {
					$classes[] = 'danger';
				}
				
				$orders .= '<tr class="' . join (' ', $classes) . '" id="' . $order->id . '">';
				foreach ($this->fields as $td) {
					$orders .= '<td>' . $order->$td . '</td>';
				}
				$orders .= '<td>' . $order->username . '</td>';
			}
			print $orders;
			?>
		</tbody>
	</table>
</div>
