<div class="panel panel-default">
	<div class="panel-heading"><?php print sprintf(View::str('all_orders_result'), $this->total_count); ?>
		<div class="pull-right table-controls">
			<?php 
				print View::link('#', '<span class="glyphicon glyphicon-filter" aria-hidden="true"></span> ' . View::str('filter'), null, 'filter', 'btn btn-xs btn-primary', View::str('filter'), null, array('toggle' => 'modal', 'target' => '#filterModal'));
				print View::link(Route::ORDER_ADD, '<span class="glyphicon glyphicon-plus" aria-hidden="true"></span> ' . View::str('add'), null, 'add', 'btn btn-xs btn-primary', null, 'top');
				print View::link(Route::ORDER_VIEW, '<span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> ' . View::str('view'), null, 'view', 'btn-action btn btn-xs btn-primary disabled', null, 'top');
				print View::link(Route::ORDER_EDIT, '<span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> ' . View::str('edit'), null, 'edit', 'btn-action btn btn-xs btn-primary disabled', null, 'top');
				print View::link(Route::ORDER_REPEAT, '<span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span> ' . View::str('repeat'), null, 'repeat', 'btn-action btn btn-xs btn-primary disabled', null, 'right');
				//print View::link(Route::ORDER_DUPLICATE, '<span class="glyphicon glyphicon-duplicate" aria-hidden="true"></span> ' . View::str('duplicate'), null, 'duplicate', 'btn-action btn btn-xs btn-primary disabled', null, 'right');
				//print View::link(Route::ORDER_DELETE, '<span class="glyphicon glyphicon-floppy-remove" aria-hidden="true"></span> ' . View::str('delete'), null, 'delete', 'btn-action btn btn-xs btn-primary disabled', null, 'right');
			?>
		</div>
	</div>
	
	<table class="table table-selected table-hover">
		<thead>
			<tr>
				<?php
				$html = '';
				foreach ($this->fields_view as $th) {
					$html .= '<th>';
					$html .= View::linkSort($th, $this->order_by);
					$html .= '</th>';
				}
				print $html;
				?>
			</tr>
		</thead>
		<tbody>
			<?php
			$orders = '';
			foreach ($this->orders as $n => $order) {
				$classes = array();
				$data = array();
				
				$classes[] = 'table_row';
				$classes[] = 'noselect';
				$classes[] = 'cursor_pointer';
				
				if ($order->isCanceled()) {
					$classes[] = 'warning';
				} else if ($order->isUrgent()) {
					$classes[] = 'urgent';
				}
				
				$data[] = 'data-can-repeat="' . ($order->canRepeat() ? '1' : '0') . '"';
				
				$orders .= '<tr class="' . join (' ', $classes) . '" ' . join (' ', $data) . ' id="' . $order->id . '">';
				foreach ($this->fields_view as $td) {
					$orders .= '<td class="td_' . $td . '">' . $order->$td . '</td>';
				}
			}
			print $orders;
			?>
		</tbody>
	</table>
</div>

<div class="paginator-block">
	<?php print View::paginator($this->totalPages, $this->currentPage); ?>
</div>