<dl class="dl-horizontal">
	<dt><?php echo $this->str('FIRSTNAME'); ?>:</dt>
	<dd><?php echo Application::$user->firstname; ?></dd>
	<dt><?php echo $this->str('LASTNAME'); ?>:</dt>
	<dd><?php echo Application::$user->lastname; ?></dd>
	<dt><?php echo $this->str('EMAIL'); ?>:</dt>
	<dd><?php echo Application::$user->email; ?></dd>
	<dt><?php echo $this->str('GROUP'); ?>:</dt>
	<dd><?php echo Application::$user->group; ?></dd>
</dl>