<div class="panel panel-default">
	<div class="panel-heading">
		<?php print View::str('photopolymers_all_list_header'); ?>
		<div class="pull-right">
			<?php print View::link(Route::POLYMER_BIND, '', null, null, 'btn btn-xs btn-primary glyphicon glyphicon-user', null, 'left'); ?>
		</div>
	</div>
	<ul class="list-group">
	<?php
	foreach ($this->photopolymers as $photopolymer) {
		print '<li class="list-group-item">' . $photopolymer->name . View::link(Route::POLYMER_DELETE, '<div class="pull-right"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></div>', 'id=' . $photopolymer->id) . '</li>';
	}
	?>
	</ul>
</div>
<hr>
<form method="post" class="form-horizontal">
<?php 
	print View::formValidate();
	print View::formNormal('photopolymer');
	print View::formNormal('id_1c');
	print View::formOffset('add', 'submit');
?>
</form>
