<div class="panel panel-default">
	<div class="panel-heading">
		<?php print $this->page->linkText(); ?>
	</div>
	<table class="table">
		<thead><tr>
			<th><?php print View::str('name'); ?></th>
			<th><?php print View::str('type'); ?></th>
			<th><?php print View::str('mandatory'); ?></th>
			<th><?php print View::str('weight'); ?></th>
			<th></th>
		</tr></thead>
		<tbody>
			<?php
			$html = '';
			foreach ($this->fields as $field) {
				$class = '';
				if ($field->isSystem()) $class = ' class="success"';
				
				$html .= '<tr' . $class . '>';
				$html .= '<td>' . $field->name . '</td>';
				$html .= '<td>' . $field->type . '</td>';
				$html .= '<td>' . View::bool2icon($field->mandatory) . '</td>';
				$html .= '<td>' . $field->weight . '</td>';
				
				$html .= '<td>';
				if ($field->canDelete()) $html .= View::link(Route::FIELD_DELETE, '', 'id=' . $field->id, 'edit', 'btn btn-xs btn-danger glyphicon glyphicon-remove', null, 'top');
				$html .= '</td>';
				
				$html .= '</tr>';
				
			}
			print $html;
			?>
		</tbody>
	</table>
</div>