<form method="post" class="form-horizontal">
	<?php 
		print View::formValidate();
		print View::formNormal('email', 'email');
		print View::formNormal('password', 'password');
		print View::formNormal('username');
		print View::formNormal('group', 'select', $this->groups);
		if (is_null($this->gid)) {
			print View::formNormal('gid');
		} else {
			print View::input('gid', 'hidden', $this->gid);
		}
		print View::formOffset('add', 'submit');
	?>
</form>