<dl class="dl-horizontal">
	<dt><?php print View::str('method'); ?>:</dt>
	<dd><?php print $this->route->path; ?></dd>
	<dt><?php print View::str('description'); ?>:</dt>
	<dd><?php print $this->route->linkTitle(); ?></dd>
	<dt><?php print View::str('request'); ?>:</dt>
	<dd><ul class="list-unstyled"><?php
		foreach ($this->form->fields as $field) {
			print '<li><b>' . $field->name . '</b> (' . $field->type . ')</li>';
		}
	?></ul></dd>
</dl>


<hr>

<form method="post" class="form-horizontal">
<?php 
	print $this->form->render();
	print View::formOffset('send', 'any', '<button id="execute" type="button" class="btn btn-primary">' . View::str('execute') . '</button>');
?>
</form>

<hr>

<form class="form-horizontal">
<?php
	print View::formNormal('response', 'textarea', null, 1);
?>
</form>