<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title><?php $this->getTitle(); ?></title>
		<?php 
			$this->getCSSfiles();
			$this->getJSfiles(); 
			$this->getJSparams();
		?>
	</head>
	<body>
		<div class="blue-bg top-first-line"></div>
		<div class="top-second-line"></div>
		<div class="white-bg container drop-shadow" id="main">
			<div class="container header">
				<a href="/"><img src="/img/repropark.jpg" id="logo"></a>
			</div>
			<div class="container" id="cols">
				<div class="row">
					<div class="col-sm-2 left">
						<?php $this->getMenu(); ?>
					</div>
					<div class="col-sm-10 content">
						<?php 
							$this->getErrors();
							$this->getContent();
						?>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>