<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="/css/bootstrap.min.css">
		<link rel="stylesheet" href="/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="/css/repropark.css">
		<script src="/js/jquery-1.11.3.min.js"></script>
		<script src="/js/bootstrap.min.js"></script>
		<script src="/js/repropark.js"></script>
		<title>Repropark</title>
	</head>
	<body>
		<div class="blue-bg top-first-line"></div>
		<div class="top-second-line"></div>
		<div class="white-bg container drop-shadow" id="main">
			<div class="container header">
				<a href="/"><img src="/img/repropark.jpg" id="logo"></a>
			</div>
			<div class="container" id="cols">
				<div class="row">
					<div class="col-sm-3 left">
						<ul class="menu">
							<?php
								foreach (Application::$routes as $route) {
									$active = Application::$route->name==$route->name;
									if ($route->isAvailable()) echo '<li class="leaf' . ($active ? ' active-trail' : '') . '"><a href="' . $route->path . '"' . ($active ? ' class="active"' : '') . '>' . $route->getValue() . '</a></li>';
								}
							?>
						</ul>
					</div>
					<div class="col-sm-9 content">
						<?php 
							foreach ($this->errors as $error) {
								echo '<div class="alert alert-danger" role="alert">' . $error . '</div>';
							}
							$this->getContent();
						?>
					</div>
				</div>
			</div>
		</div>
	</body>
</html>