<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="/css/bootstrap.min.css">
		<link rel="stylesheet" href="/css/bootstrap-theme.min.css">
		<link rel="stylesheet" href="/css/repropark.css">
		<script src="/js/jquery-1.11.3.min.js"></script>
		<script src="/js/bootstrap.min.js"></script>
		<title>Repropark</title>
	</head>
	<body>
		<div class="blue-bg top-first-line"></div>
		<div class="top-second-line"></div>
		<div class="white-bg container drop-shadow" id="main">
			<div class="container header">
				<a href="#"><img src="/img/repropark.jpg" id="logo"></a>
			</div>
			<div class="container" id="cols">
				<div class="left">
					<ul class="menu">
						<li class="leaf first active-trail"><a href="/home" class="active">Главная</a></li>
						<li class="leaf"><a href="/account">Аккаунт</a></li>
						<li class="leaf last"><a href="/contacts">Контакты</a></li>
					</ul>
				</div>
				<div class="content">
					<?php echo $this->getContent(); ?>
				</div>
			</div>
		</div>
	</body>
</html>